### ISSUE TITLE
Create 3 Tables of Summary Statistics

### ISSUE THREAD

**Issue by dustinkincaid** [ReproducibleQM/gReen2O#11]
Create tables of summary statistics (mean, sd, n) for each region and lake type. The tables will be separated by physical, chemical, and loading variables.

**Comment by dustinkincaid** [comment]
I created R code for the summary statistics. Dumb dumb over here doesn't know how to read a file directly from GitHub so need to change code to do that.

**Comment by jsta** [comment]
I made some adjustments to the table code. Among other things, it now prints the table output to a file in the `07_tables` folder.

**Comment by jsta** [comment]
This process would be a bit simpler if we switched to using Rmarkdown.

**Comment by nagelkirk** [comment]
I'd be for that

On Tue, Apr 11, 2017 at 11:48 AM, Joseph Stachelek <notifications@github.com

**Comment by jsta** [comment]
Ok, I went ahead and dropped the `lake_type` distinction from the tables. This makes it possible to combine all the tables on to one page (see [07_tables/big_table.pdf](https://github.com/ReproducibleQM/NES/blob/master/07_tables/big_table.pdf)). I can revert to the old style if we like that better.

**Comment by jsta** [comment]
We might want to consider remaking our table with https://github.com/kaz-yos/tableone

**Comment by jsta** [comment]
I am thinking of remaking the table with one of the tools mentioned in _github.com/ropensci/unconf17/issues/69_. Also I am going to explore splitting out the sample size (n) info to a separate table.
