### ISSUE TITLE
Plotting summary data

### ISSUE THREAD

**Issue by cbahlai** [ReproducibleQM/gReen2O#12]
Should we use ggplot or base R?

Here's a ggplot mapping tutorial:
http://zevross.com/blog/2014/07/16/mapping-in-r-using-the-ggplot2-package/

**Comment by jsta** [comment]
Using ggplot with the `sf` package:
http://strimas.com/r/tidy-sf/

**Comment by nagelkirk** [comment]
Cool - thanks!

On Thu, Mar 16, 2017 at 11:31 AM, Joseph Stachelek <notifications@github.com

**Comment by nagelkirk** [comment]
ggplot was a bit of a pain, so I went with the plot function from base R/raster. Current results are in the mapping folder!

**Comment by jsta** [comment]
Do you think it would be a good idea to drop the coordinate tick marks? I think we should figure out how to trim the extra whitespace from the figure margins (see the repo README).

**Comment by nagelkirk** [comment]
Definitely. I'm bringing a printed one to class for next time so that we
can circle and scribble stuff about what we'd like changed. I wasn't going
to start editing them too much until I had more input.
