### ISSUE TITLE
Case 585 of n_total is negative

### ISSUE THREAD

**Issue by nagelkirk** [ReproducibleQM/gReen2O#18]

**Comment by jsta** [comment]
It appears to be negative on the original pdf.

**Comment by jsta** [comment]
The entry is PDF 476, page 62

**Comment by nagelkirk** [comment]
Is that a possible value? I think we actually even talked about that at
some point and decided to leave it negative. I already changed the plotting
code to deal with it, so I think leaving it would be fine.
