### ISSUE TITLE
Finish maps with labels and correct coordinates

### ISSUE THREAD

**Issue by nagelkirk** [ReproducibleQM/gReen2O#21]
* [x] Change coordinates to lat long
* [x] Create legends inside the plot
* [x] Move title inside the plot (moving these inside the plot allows them to be stacked in a 2x3 plot later.
* [x] log transform and plot the data

**Comment by nagelki4** [comment]
* [ ] Change coordinates to lat long
* [ ] Create legends inside the plot
* [ ] Move title inside the plot (moving these inside the plot allows them to be stacked in a 2x3 plot later.
* [ ] log transform and plot the data

**Comment by nagelkirk** [comment]
With the projection I've chosen, you can't have lat and long on the axes because the US is curved (thanks to the projection...and, I mean, reality). I could do another projection, but then it's not as aesthetically pleasing because it stretches and squeezes diff parts of the US, and the projection I'm currently using is the one used most often (in my experience) when doing a simple figure of the US in articles. So I'm thinking to just do what other people have done, and not include lat/long coords.
