### ISSUE TITLE
Add "Author Contribution" in draft article

### ISSUE THREAD

**Issue by mill2735** [ReproducibleQM/gReen2O#22]
Each of us needs to write something for this, so I'm assigning this to all those who currently have nothing in this section of the draft article

**Comment by jsta** [comment]
Do we want to write one sentence per person or one sentence per task? How general should we be on this? My preference would be to keep it general and write one sentence per task with the following tasks:

*  writing
*  data analysis
*  data QA
*  data collection

I am new to this so I don't know what the norms are. What do other people think?

**Comment by kingka21** [comment]
I think we should be very general and just have one sentence per task (I read a paper yesterday that was general and I liked it). 

Something like:

"All authors contributed to data quality assurance and edited the article text. JS conceived the study and implemented the optical character recognition code.   CF, DK, and RN performed the data analysis and made figures. KK, HM, and JS wrote major parts of the manuscript text."

Quoting Joseph Stachelek <notifications@github.com>:

**Comment by jsta** [comment]
Sounds great. I went ahead and replaced the old text with what you have here.
