### ISSUE TITLE
Convert Google Doc to LaTeX

### ISSUE THREAD

**Issue by jsta** [ReproducibleQM/gReen2O#24]
After we have the MS finalized as a Google Doc, I think it would be a good idea to prepare our submission in LaTeX rather than MS Word given our reproducible and open science focus. 

Is anyone willing to do this who is either interested in learning LaTeX (or already knowledgeable in LaTeX)? I can but I don't want to take away the opportunity from someone interested in learning. The process can be done in RStudio (http://keziamanlove.com/latex-in-rstudio/).

**Comment by mill2735** [comment]
I'd like to learn & do this, if no one else objects?

**Comment by jsta** [comment]
The page I linked above assumes you would work in raw LaTeX. Alternatively, you can use Rmarkdown which will generate a LaTeX `tex` file for you. If you go this route, I suggest looking at https://github.com/Pakillo/rmdTemplates

**Comment by jsta** [comment]
Unfortunately, it looks like we cannot use Rmarkdown. Our target journal has [fairly specific instructions for LaTeX prep](http://www.earth-system-science-data.net/for_authors/manuscript_preparation.html):

> Please download the Copernicus Publications LaTeX Package to prepare your manuscript. The package contains the LaTeX2e class file, the configuration file, all needed style files, as well as a template serving as the framework for your manuscript. Please download the Copernicus Publications LaTeX Package, version 4.5, 24 March 2017.

> Authors are kindly requested to make use of the template.tex file embedded in the LaTeX Package since most of the definitions for the structure of manuscript elements are described there. Since we convert all typeset TeX files into XML, the expressions and markups have to be highly standardized. Therefore, please keep the following in mind:

> * Please provide only one figure file for figures with several panels, and please do not use \subfloat or similar commands.
> * Please use only commands in which words, numbers, etc. are within braces (e.g. \textrm{TEXT} instead of {\rm TEXT}).
  >  For algorithms, please use the syntax given in template.tex or provide your algorithm as a figure.
> * Please do not define new commands.
    The most commonly used packages (\usepackage{}) are integrated in the copernicus.cls. Some other packages often used by the community are defined in template.tex. Please do not insert additional ones in your *.tex file.
    Spaces in labels (\label{}) are not allowed; please make sure that no label name is assigned more than once.
  > * Please do not use \paragraph{}; only \subsubsection{} is allowed.
    It is not possible to add tables in colour.

> If you are familiar with BibTeX, you can use copernicus.bst from the package. It will sort your bibliography entries alphabetically and produce the proper layout of the reference list.

**Also, they require that we use [their template](http://www.earth-system-science-data.net/Copernicus_LaTeX_Package.zip)**.

@mill2735 Does this affect your decision to take this on?

**Comment by mill2735** [comment]
Nope..don't think so.  I'll let you know how it goes, and solicit "expert help" if I run into troubles.  Okay?

**Comment by jsta** [comment]
OK. You might consider creating a new folder in the repository (something like `08_manuscript`) with the LaTeX files so we can follow along on the progress.
