### ISSUE TITLE
Research questions

### ISSUE THREAD

**Issue by jsta** [ReproducibleQM/gReen2O#4]
Here are some potential research questions:

* Are differences between the 2007 NLA and the NES related to specific factors?

* How do depth estimates compare with more recent depth model predictions?

* How does the NES compare with the 2012 NLA results?

 Please add more below!

**Comment by kingka21** [comment]
@jsta @dustinkincaid @mill2735 @chanse-ford 

Hi Everyone, 

We linked a google doc and the scanned copy of the data to the read.me.  We have started a list of questions.  Please look at the data and feel free to comment with other potential research questions.  We can discuss and pick one next week. 

We have also decided to use the issues tab to leave comments and write discussions.

**Comment by jsta** [comment]
Moved these to the ms draft discussion section
