### ISSUE TITLE
Target journal

### ISSUE THREAD

**Issue by jsta** [ReproducibleQM/gReen2O#6]
There is a great list of data paper journals here: https://www.wiki.ed.ac.uk/display/datashare/Sources+of+dataset+peer+review

The only one I found that does not charge is:
http://www.earth-system-science-data.net/for_authors/article_processing_charges.html

**Comment by cbahlai** [comment]
There's a good chance that we'd be able to get a 'fee waiver' - given this is cleaning government data into a usable form with no direct grant support, so don't eliminate those with fees entirely yet! If you have some in mind, I can make some informal inquiries.

**Comment by cbahlai** [comment]
An editor of the data journal "Data" has encouraged us to submit there- there are no page charges:

http://www.mdpi.com/journal/data

I've just sent him a bit more of a specific inquiry, will let you know what he says !

**Comment by cbahlai** [comment]
Where did we end up on this? Ecological Archives?

**Comment by jsta** [comment]
Yes, that is our current target pub. We made an initial inquiry with the editor to ask about whether the paper would be considered. We have yet to hear back.

**Comment by mill2735** [comment]
I contacted the Data Editor of ESA EcoArchives [william.michener@gmail.com] on March 6th and have yet to receive a response.  My next step is to follow-up with the Associate Data Editor: Jane L. Bain <jlb40@cornell.edu>.

**Comment by cbahlai** [comment]
Cool- since this is pending, let's keep the issue open in case we need followup!  Let me know if you need me to step in and twitter-shame anyone.

**Comment by mill2735** [comment]
I followed up with the Data Editor as ESA, and finally received his response:  _The metadata requirements cannot be subverted for Data Papers.  Furthermore, the data you describe do not align well with ESA Data Papers.  You may wish to look at the KNB data repository._

So...I'll look into the KNB data repository per his suggestion, unless Christie has another suggestion?

**Comment by cbahlai** [comment]
Hmm...let's discuss in seminar tomorrow. KNB would be appropriate, but it's more a stand-alone repository for archiving data associated with papers, as I understand, and this is more of a 'data paper' since you'll be providing summary stats, figs and talking a bit more about the data cleaning methods.

**Comment by jsta** [comment]
I think further discussion on this issue should occur in the associated Google doc.
