### ISSUE TITLE
Syncing Problems

### ISSUE THREAD

**Issue by nagelkirk** [ReproducibleQM/gReen2O#7]
Hi all, 

For some reason I'm having sync errors with csv's 476 and 477. I don't want to do anything with those, so I just shut down github desktop. Is anyone else having issues when the sync?

- Ryan

**Comment by jsta** [comment]
Have you done anything to those files? You could try the following steps to recover:

* save a copy of your 475 file outside of the repository,
* delete your local copy of the repository
* pull the remote repo to make a new local repo
* move your 475 copy to the new local repo
* sync with remote

@cbahlai

**Comment by nagelkirk** [comment]
I didn't do anything to those files, but will try this later!

Ryan
